Repository SixLabors/ImageSharp.Web, pull requests merged in 2020-09, with the labels that each got.

#115 Simplify Dependency Injection
  README.md
  samples/ImageSharp.Web.Sample/Startup.cs
  src/ImageSharp.Web/Caching/CacheHash.cs
  src/ImageSharp.Web/DependencyInjection/ImageSharpBuilderExtensions.cs
  src/ImageSharp.Web/DependencyInjection/ServiceCollectionExtensions.cs
  src/ImageSharp.Web/FormatUtilities.cs
  tests/ImageSharp.Web.Benchmarks/Caching/CacheHashBenchmarks.cs
  tests/ImageSharp.Web.Tests/Caching/CacheHashTests.cs
  tests/ImageSharp.Web.Tests/DependencyInjection/ServiceRegistrationExtensionsTests.cs
  tests/ImageSharp.Web.Tests/Helpers/FormatUtilitiesTests.cs
Labels: api, breaking

#100 Converts callbacks to async
  samples/ImageSharp.Web.Sample/Startup.cs
  src/ImageSharp.Web/Middleware/ImageContext.cs
  src/ImageSharp.Web/Middleware/ImageSharpMiddleware.cs
  src/ImageSharp.Web/Middleware/ImageSharpMiddlewareOptions.cs
  src/ImageSharp.Web/Middleware/ResponseConstants.cs
  tests/ImageSharp.Web.Tests/TestUtilities/AzureBlobStorageCacheTestServerFixture.cs
  tests/ImageSharp.Web.Tests/TestUtilities/PhysicalFileSystemCacheTestServerFixture.cs
Labels: breaking, enhancement

#116 Fix compatibility with NET 5 SDK InternalsVisibleTo
  global.json
  src/Directory.Build.props
  src/Directory.Build.targets
  src/ImageSharp.Web/DependencyInjection/ImageSharpBuilderExtensions.cs
Labels: build

#117 Make converters injectable and respect culture
  src/ImageSharp.Web/Commands/CommandDescriptor.cs
  src/ImageSharp.Web/Commands/CommandParser.cs
  src/ImageSharp.Web/Commands/Converters/ArrayConverter{T}.cs
  src/ImageSharp.Web/Commands/Converters/ColorConverter.cs
  src/ImageSharp.Web/Commands/Converters/CommandConverter.cs
  src/ImageSharp.Web/Commands/Converters/EnumConverter.cs
  src/ImageSharp.Web/Commands/Converters/ICommandConverter.cs
  src/ImageSharp.Web/Commands/Converters/IntegralNumberConverter{T}.cs
  src/ImageSharp.Web/Commands/Converters/ListConverter{T}.cs
  src/ImageSharp.Web/Commands/Converters/SimpleCommandConverter{T}.cs
  src/ImageSharp.Web/Commands/TypeConstants.cs
  src/ImageSharp.Web/DependencyInjection/ImageSharpBuilderExtensions.cs
  src/ImageSharp.Web/DependencyInjection/ServiceCollectionExtensions.cs
  src/ImageSharp.Web/Middleware/ImageCommandContext.cs
  src/ImageSharp.Web/Middleware/ImageSharpMiddleware.cs
  src/ImageSharp.Web/Middleware/ImageSharpMiddlewareOptions.cs
  src/ImageSharp.Web/Processors/BackgroundColorWebProcessor.cs
  src/ImageSharp.Web/Processors/FormatWebProcessor.cs
  src/ImageSharp.Web/Processors/IImageWebProcessor.cs
  src/ImageSharp.Web/Processors/ResizeWebProcessor.cs
  src/ImageSharp.Web/Processors/WebProcessingExtensions.cs
  tests/ImageSharp.Web.Tests/Commands/CommandParserTests.cs
  tests/ImageSharp.Web.Tests/DependencyInjection/MockCommandConverter.cs
  tests/ImageSharp.Web.Tests/DependencyInjection/MockWebProcessor.cs
  tests/ImageSharp.Web.Tests/DependencyInjection/ServiceRegistrationExtensionsTests.cs
  tests/ImageSharp.Web.Tests/Processing/AzureBlobStorageCacheServerTests.cs
  tests/ImageSharp.Web.Tests/Processing/PhysicalFileSystemCacheServerTests.cs
  tests/ImageSharp.Web.Tests/Processors/BackgroundColorWebProcessorTests.cs
  tests/ImageSharp.Web.Tests/Processors/FormatWebProcessorTests.cs
  tests/ImageSharp.Web.Tests/Processors/ResizeWebProcessorTests.cs
  tests/ImageSharp.Web.Tests/TestUtilities/AzureBlobStorageCacheTestServerFixture.cs
  tests/ImageSharp.Web.Tests/TestUtilities/CacheBusterWebProcessor.cs
  tests/ImageSharp.Web.Tests/TestUtilities/PhysicalFileSystemCacheTestServerFixture.cs
Labels: api, breaking

#119 Add Parallel Identical Query Tests.
  .github/workflows/build-and-test.yml
  samples/ImageSharp.Web.Sample/wwwroot/index.html
  src/ImageSharp.Web/FormatUtilities.cs
  tests/ImageSharp.Web.Tests/Processing/AzureBlobStorageCacheServerTests.cs
  tests/ImageSharp.Web.Tests/Processing/PhysicalFileSystemCacheServerTests.cs
Labels: tests

#125 Allow the ability to set the quality of jpegs.
  samples/ImageSharp.Web.Sample/Startup.cs
  samples/ImageSharp.Web.Sample/wwwroot/index.html
  src/ImageSharp.Web/DependencyInjection/ServiceCollectionExtensions.cs
  src/ImageSharp.Web/FormattedImage.cs
  src/ImageSharp.Web/Middleware/ImageProcessingContext.cs
  src/ImageSharp.Web/Processors/FormatWebProcessor.cs
  src/ImageSharp.Web/Processors/JpegQualityWebProcessor.cs
  tests/ImageSharp.Web.Tests/DependencyInjection/ServiceRegistrationExtensionsTests.cs
  tests/ImageSharp.Web.Tests/Processors/FormattedImageTests.cs
  tests/ImageSharp.Web.Tests/Processors/JpegQualityWebProcessorTests.cs
  tests/ImageSharp.Web.Tests/TestUtilities/AzureBlobStorageCacheTestServerFixture.cs
  tests/ImageSharp.Web.Tests/TestUtilities/PhysicalFileSystemCacheTestServerFixture.cs
Labels: enhancement
