Repository SixLabors/ImageSharp.Web, pull requests merged in 2022-02, with the labels that each got.

#213 Add CacheFolderDepth option and create shorter file names
  samples/ImageSharp.Web.Sample/Startup.cs
  src/ImageSharp.Web/Caching/PhysicalFileSystemCache.cs
  src/ImageSharp.Web/Caching/PhysicalFileSystemCacheOptions.cs
  src/ImageSharp.Web/Caching/SHA256CacheHash.cs
  src/ImageSharp.Web/DependencyInjection/ServiceCollectionExtensions.cs
  src/ImageSharp.Web/Middleware/ImageSharpMiddleware.cs
  src/ImageSharp.Web/Middleware/ImageSharpMiddlewareOptions.cs
  tests/ImageSharp.Web.Benchmarks/Caching/CacheHashBenchmarks.cs
  tests/ImageSharp.Web.Benchmarks/Caching/StringJoinBenchmarks.cs
  tests/ImageSharp.Web.Tests/Caching/CacheHashTests.cs
  tests/ImageSharp.Web.Tests/Caching/PhysicialFileSystemCacheTests.cs
  tests/ImageSharp.Web.Tests/DependencyInjection/ServiceRegistrationExtensionsTests.cs
Labels: breaking, api

#214 Decouple PhysicalFileSystemProvider from WebRootFileProvider
  src/Directory.Build.targets
  src/ImageSharp.Web/Caching/LegacyV1CacheKey.cs
  src/ImageSharp.Web/Caching/PhysicalFileSystemCache.cs
  src/ImageSharp.Web/Caching/PhysicalFileSystemCacheOptions.cs
  src/ImageSharp.Web/DependencyInjection/ImageSharpBuilderExtensions.cs
  src/ImageSharp.Web/Middleware/ImageSharpMiddlewareOptions.cs
  src/ImageSharp.Web/Providers/PhysicalFileSystemProvider.cs
  src/ImageSharp.Web/Providers/PhysicalFileSystemProviderOptions.cs
  tests/ImageSharp.Web.Tests/Caching/PhysicialFileSystemCacheTests.cs
  tests/ImageSharp.Web.Tests/Providers/PhysicalFileSystemProviderTests.cs
Labels: enhancement, api

#215 Add AutoOrientWebProcessor
  samples/ImageSharp.Web.Sample/Startup.cs
  src/ImageSharp.Web/DependencyInjection/ServiceCollectionExtensions.cs
  src/ImageSharp.Web/Processors/AutoOrientWebProcessor.cs
  tests/ImageSharp.Web.Tests/Processors/AutoOrientWebProcessorTests.cs
Labels: enhancement, api

#217 Respect EXIF orientation when resizing
  .github/workflows/build-and-test.yml
  src/Directory.Build.targets
  src/ImageSharp.Web/ImageSharp.Web.csproj
  src/ImageSharp.Web/Processors/ResizeWebProcessor.cs
  tests/ImageSharp.Web.Tests/Processors/ResizeWebProcessorTests.cs
Labels: enhancement, breaking, api

#219 Separate AWS cache options and normalize implementations
  src/ImageSharp.Web.Providers.AWS/AmazonS3ClientFactory.cs
  src/ImageSharp.Web.Providers.AWS/Caching/AWSS3StorageCache.cs
  src/ImageSharp.Web.Providers.AWS/Caching/AWSS3StorageCacheOptions.cs
  src/ImageSharp.Web.Providers.AWS/IAWSS3BucketClientOptions.cs
  src/ImageSharp.Web.Providers.AWS/Providers/AWSS3StorageImageProviderOptions.cs
  src/ImageSharp.Web.Providers.Azure/Caching/AzureBlobStorageCacheOptions.cs
  src/ImageSharp.Web.Providers.Azure/IAzureBlobContainerClientOptions.cs
  src/ImageSharp.Web.Providers.Azure/Providers/AzureBlobStorageImageProviderOptions.cs
  tests/ImageSharp.Web.Tests/TestUtilities/AWSS3StorageCacheTestServerFixture.cs
Labels: azure, aws, api

#220 Removed the AutoOrientWebProcessor.
  samples/ImageSharp.Web.Sample/Startup.cs
  src/ImageSharp.Web/DependencyInjection/ServiceCollectionExtensions.cs
  src/ImageSharp.Web/Processors/AutoOrientWebProcessor.cs
  tests/ImageSharp.Web.Tests/Processors/AutoOrientWebProcessorTests.cs
Labels: api

#221 Apply updates to XY and Anchor positions based on EXIF metadata
  .github/CONTRIBUTING.md
  samples/ImageSharp.Web.Sample/wwwroot/Landscape_0.jpg
  samples/ImageSharp.Web.Sample/wwwroot/Landscape_1.jpg
  samples/ImageSharp.Web.Sample/wwwroot/Landscape_2.jpg
  samples/ImageSharp.Web.Sample/wwwroot/Landscape_3.jpg
  samples/ImageSharp.Web.Sample/wwwroot/Landscape_4.jpg
  samples/ImageSharp.Web.Sample/wwwroot/Landscape_5.jpg
  samples/ImageSharp.Web.Sample/wwwroot/Landscape_6.jpg
  samples/ImageSharp.Web.Sample/wwwroot/Landscape_7.jpg
  samples/ImageSharp.Web.Sample/wwwroot/Landscape_8.jpg
  samples/ImageSharp.Web.Sample/wwwroot/Portrait_0.jpg
  samples/ImageSharp.Web.Sample/wwwroot/Portrait_1.jpg
  samples/ImageSharp.Web.Sample/wwwroot/Portrait_2.jpg
  samples/ImageSharp.Web.Sample/wwwroot/Portrait_3.jpg
  samples/ImageSharp.Web.Sample/wwwroot/Portrait_4.jpg
  samples/ImageSharp.Web.Sample/wwwroot/Portrait_5.jpg
  samples/ImageSharp.Web.Sample/wwwroot/Portrait_6.jpg
  samples/ImageSharp.Web.Sample/wwwroot/Portrait_7.jpg
  samples/ImageSharp.Web.Sample/wwwroot/Portrait_8.jpg
  samples/ImageSharp.Web.Sample/wwwroot/index.html
  src/Directory.Build.targets
  src/ImageSharp.Web/FormattedImage.cs
  src/ImageSharp.Web/Middleware/ImageSharpMiddleware.cs
  src/ImageSharp.Web/Processors/ResizeWebProcessor.cs
  tests/ImageSharp.Web.Tests/Processors/ResizeWebProcessorTests.cs
Labels: enhancement, breaking, api
