Repository SixLabors/ImageSharp.Web, pull requests merged in 2022-04, with the labels that each got.

#241 Expose ExifOrientationUtilities and ICommandConverter implementations
  samples/ImageSharp.Web.Sample/wwwroot/index.html
  src/ImageSharp.Web/Caching/PhysicalFileSystemCache.cs
  src/ImageSharp.Web/Commands/Converters/ArrayConverter{T}.cs
  src/ImageSharp.Web/Commands/Converters/ColorConverter.cs
  src/ImageSharp.Web/Commands/Converters/EnumConverter.cs
  src/ImageSharp.Web/Commands/Converters/IntegralNumberConverter{T}.cs
  src/ImageSharp.Web/Commands/Converters/ListConverter{T}.cs
  src/ImageSharp.Web/ExifOrientationUtilities.cs
  src/ImageSharp.Web/FormatUtilities.cs
  src/ImageSharp.Web/FormattedImage.cs
  src/ImageSharp.Web/Middleware/ImageSharpMiddlewareOptions.cs
  src/ImageSharp.Web/PathUtilities.cs
  src/ImageSharp.Web/Processors/ResizeWebProcessor.cs
  src/ImageSharp.Web/Providers/PhysicalFileSystemProvider.cs
  tests/ImageSharp.Web.Tests/Helpers/ExifOrientationUtilitiesTests.cs
  tests/ImageSharp.Web.Tests/Processors/ResizeWebProcessorTests.cs
Labels: api

#247 Add InsertProvider extensions and tests
  src/ImageSharp.Web/DependencyInjection/ImageSharpBuilderExtensions.cs
  tests/ImageSharp.Web.Tests/DependencyInjection/ServiceRegistrationExtensionsTests.cs
Labels: enhancement, api

#246 PhysicalFileSystem optimizations
  src/Directory.Build.targets
  src/ImageSharp.Web/Caching/PhysicalFileSystemCache.cs
  src/ImageSharp.Web/ImageCacheMetadata.cs
  src/ImageSharp.Web/ImageSharp.Web.csproj
  src/ImageSharp.Web/Providers/FileProviderImageProvider.cs
  src/ImageSharp.Web/Providers/PhysicalFileSystemProvider.cs
  src/ImageSharp.Web/Providers/PhysicalFileSystemProviderOptions.cs
  src/ImageSharp.Web/Providers/WebRootImageProvider.cs
  src/ImageSharp.Web/Resolvers/PhysicalFileSystemCacheResolver.cs
  src/ImageSharp.Web/Resolvers/PhysicalFileSystemResolver.cs
Labels: enhancement

#250 Add HMAC authentication options.
  src/ImageSharp.Web/Caching/SHA256CacheHash.cs
  src/ImageSharp.Web/Caching/UriAbsoluteCacheKey.cs
  src/ImageSharp.Web/Caching/UriAbsoluteLowerInvariantCacheKey.cs
  src/ImageSharp.Web/Caching/UriRelativeCacheKey.cs
  src/ImageSharp.Web/Caching/UriRelativeLowerInvariantCacheKey.cs
  src/ImageSharp.Web/CaseHandlingUriBuilder.cs
  src/ImageSharp.Web/Commands/Converters/SimpleCommandConverter{T}.cs
  src/ImageSharp.Web/HMACUtilities.cs
  src/ImageSharp.Web/Middleware/ImageSharpMiddleware.cs
  src/ImageSharp.Web/Middleware/ImageSharpMiddlewareOptions.cs
  tests/ImageSharp.Web.Tests/Helpers/HMACUtilitiesTests.cs
  tests/ImageSharp.Web.Tests/Processing/PhysicalFileSystemCacheAuthenticatedServerTests.cs
  tests/ImageSharp.Web.Tests/TestUtilities/AuthenticatedServerTestBase.cs
  tests/ImageSharp.Web.Tests/TestUtilities/AuthenticatedTestServerFixture.cs
  tests/ImageSharp.Web.Tests/TestUtilities/PhysicalFileSystemCacheAuthenticatedTestServerFixture.cs
  tests/ImageSharp.Web.Tests/TestUtilities/ServerTestBase.cs
  tests/ImageSharp.Web.Tests/TestUtilities/TestServerFixture.cs
Labels: enhancement, api, security

#249 Make InsertProvider idempotent and remove reflection
  src/ImageSharp.Web/DependencyInjection/ImageSharpBuilderExtensions.cs
  src/ImageSharp.Web/ImageSharp.Web.csproj
  tests/ImageSharp.Web.Tests/DependencyInjection/ServiceRegistrationExtensionsTests.cs
Labels: bug, api

#245 Remove no-op ImageSharpConfiguration and setup action
  src/ImageSharp.Web/DependencyInjection/ImageSharpConfiguration.cs
  src/ImageSharp.Web/DependencyInjection/ServiceCollectionExtensions.cs
Labels: api
